### ISSUE TITLE
Support for Docker Compose

### ISSUE THREAD

**Issue by jsierles** [seek-oss/docker-ecr-cache-buildkite-plugin#21]
We use Buildkite with Compose so we can run secondary services like redis and postgres. Is it possible to use this plugin with compose-based builds?

**Comment by baxang** [comment]
I ran into this need lately and, although it's not an ideal solution, came up with a hacky workaround. I hope someone might find it useful.

Due to the way docker-compose plug-in works (more about it later), I could only come up with a hacky way to do this.

docker-compose plugin has a mechanism to detect pre-built images by checking meta-data. The default metadata key is `docker-compose-plugin-built-image-tag-$service` so by setting an image name/tag to this you can trick the plugin to use an image of your choice. However, the key name is made up of config file names when custom config files are used.

With this knowledge, this plugin exports the cache image's name and tag to `$BUILDKITE_PLUGIN_DOCKER_IMAGE`. We can use this to store the image name in meta-data with the "right" key so docker-compose plugin will pick it up in later steps. As mentioned earlier, the key format changes per config, so I included both default and customised cases in the below example code.

`test 1` will pick up `docker-compose-plugin-built-image-tag-app` and `test 2` will use `docker-compose-plugin-built-image-tag-app-docker-compose.yml-docker-compose.extra.yml`. See the linked `metadata.bash` for how it is computed.

```yml
steps:
  - label: ":docker: Build Docker image"
    commands:
      # A hack to pass the Docker image name:tag to docker-compose plugin's run.
      # This relies on the implementation of docker-compose plugin:
      #   https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/blob/v3.7.0/lib/metadata.bash#L28-L43
      - buildkite-agent meta-data set docker-compose-plugin-built-image-tag-app $$BUILDKITE_PLUGIN_DOCKER_IMAGE
      - buildkite-agent meta-data set docker-compose-plugin-built-image-tag-app-docker-compose.yml-docker-compose.extra.yml $$BUILDKITE_PLUGIN_DOCKER_IMAGE
    plugins:
      - seek-oss/docker-ecr-cache#v1.9.0:
          target: test
          cache-on:
            - yarn.lock
            - Gemfile.lock

  - wait: ~

  - label: "test 1"
    plugins:
      - docker-compose#v3.7.0:
          run: app

  - label: "test2"
    plugins:
      - docker-compose#v3.7.0:
          run: app
          config:
            - docker-compose.yml
            - docker-compose.extra.yml
```

**Comment by 72636c** [comment]
It's possible to use the cached image as one of the services in your `docker-compose.yml`:

```yaml
services:
  app:
    image: ${BUILDKITE_PLUGIN_DOCKER_IMAGE:-''}
```
