### ISSUE TITLE
Provide steps in YAML instead of Dockerfile

### ISSUE THREAD

**Issue by koterpillar** [seek-oss/docker-ecr-cache-buildkite-plugin#32]
I'd like to share a common pipeline between several repositories, where the actual repositories' YAML is `aws s3 cp ... - | bash | buildkite-pipeline upload` and the script stored in S3 does the work. And to speed up the builds, I'd like to utilise the ECR caching in the common pipeline. However, the repositories won't know any of this and will not have a Dockerfile to enable the plugin to work.

I'd like to be able to specify something like this _instead_ of a Dockerfile:

```yaml
steps:
  - command: npm test
    plugins:
      - seek-oss/docker-ecr-cache#v1.9.0:
          cache-on:
            - package-lock.json
          base-image: node:10-alpine
          steps:
            - npm install
            - curl large_file ...
            - ...
```

Another option that would solve this problem is specifying a Dockerfile location in S3.
