### ISSUE TITLE
add ability to use an image on a cache miss

### ISSUE THREAD

**Issue by ivotron** [seek-oss/docker-ecr-cache-buildkite-plugin#42]
first of all thanks a lot for this plugin! 🙇

if I understand correctly from reading the [Design section of the README](https://github.com/seek-oss/docker-ecr-cache-buildkite-plugin#design), the image is built from scratch on a cache miss, is this correct? What would it take to add the ability of having a tag that can be used to reference it in the `--cache-from` arg for `docker build` in the case of cache misses? would you be open to having a PR that adds this functionality?

thanks!

**Comment by gitlon** [comment]
@ivotron 

a PR seems ok, but I think you can achieve what you want with the current plugin using `additional-build-args`, ref [README](https://github.com/seek-oss/docker-ecr-cache-buildkite-plugin#specifying-build-args)?

eg:

```yaml
steps:
  - command: echo hello
    plugins:
      - seek-oss/docker-ecr-cache#v2.0.0:
          additional-build-args: '--cache-from somereg/my-image:tag'
      - docker#v3.12.0
```
